image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
 - check
 - test
 - run

quality_checker:
  stage: check
  before_script:
   - echo "installing pylint"
   - pip install pylint
   - echo "installing pylint done"
  script:
   - echo "checking source code with pylint"
   - pylint LoggerModule.py
   - pylint RuntimeModule.py
   - pylint CheckModule.py
   - pylint Gui.py
   - echo "linting done"

test:
  stage: test
  script:
   - echo "start unit test"
   - python -m unittest CheckModuleTest
  after_script:
   - echo "unit test done"

run:
  stage: run
  script:
   - python RuntimeModule.py
   
   pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
